name: todo_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.1
  hooks_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  flutter_vector_icons: ^2.0.0
  smooth_page_indicator: ^1.1.0
  country_picker: ^2.0.26
  pinput: ^4.0.0
  date_time_picker: ^2.1.0
  dynamic_color: ^1.7.0
  flutter_datetime_picker_plus: ^2.2.0
  riverpod_annotation: ^2.3.5
  firebase_auth: ^4.20.0
  flutter_local_notifications: ^17.1.2
  flutter_hooks: ^0.20.5
  sqflite: ^2.3.3+1
  intl: ^0.17.0
  fl_chart: ^0.68.0



dev_dependencies:
  build_runner: ^2.4.10
  riverpod_generator: ^2.4.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/































